### ISSUE TITLE
Snippet execution (and replacement)

### ISSUE THREAD

**Issue by ghbrown** [mfontanini/presenterm-export#11]
`+exec` and  `+exec_replace` don't seem to work when exporting using the following command:
```bash
presenterm --enable-snippet-execution-replace --image-protocol kitty-local --export-pdf presentation/presentation.md
```

`+exec` blocks do not have the corresponding output, while `+exec_replace` blocks turn into
```
<code block containing code to be executed>
snippet execution is disabled
```

Otherwise the PDF looks good, and other blocks like `latex +render` are also fine.
I would have expected to see an issue about this here already, so perhaps I'm making a mistake.

**Comment by mfontanini** [comment]
Thanks for the report! This is fixed in https://github.com/mfontanini/presenterm/pull/371. I'm in the process of rewriting the PDF generation so it doesn't need presenterm-export anymore and as an added bonus issues like this one won't happen anymore.

**Comment by ghbrown** [comment]
Thanks for the quick fix. Very exciting about built-in export functionality!
